//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MueblesTerminadosV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tpresupuestoLineas
    {
        public string codigoPresupuesto { get; set; }
        public int codigo { get; set; }
        public string referencia { get; set; }
        public string familia { get; set; }
        public string articulo { get; set; }
        public Nullable<int> diseno { get; set; }
        public string serie { get; set; }
        public string descripcion { get; set; }
        public string color { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> dto { get; set; }
        public Nullable<double> IVA { get; set; }
        public string nombreDisenoPresupuestado { get; set; }
        public Nullable<byte> siSerieImportada { get; set; }
        public Nullable<byte> siDisenoImportado { get; set; }
        public Nullable<double> coste { get; set; }
        public Nullable<double> baseImponible { get; set; }
        public Nullable<int> codigoPersiana { get; set; }
        public string tipoFactura { get; set; }
        public Nullable<double> anchuraFigura { get; set; }
        public Nullable<double> alturaFigura { get; set; }
        public Nullable<double> fondoFigura { get; set; }
        public Nullable<int> codigoPremarco { get; set; }
        public Nullable<int> codigoCuarteron { get; set; }
        public Nullable<int> tipoCuarteron { get; set; }
        public string codigoPedido { get; set; }
        public string codigoAlbaran { get; set; }
        public string codigoFactura { get; set; }
        public Nullable<double> dto2 { get; set; }
        public Nullable<double> comision { get; set; }
        public Nullable<System.DateTime> fechaservir { get; set; }
        public Nullable<System.DateTime> fechaservido { get; set; }
        public Nullable<int> unidadprecio { get; set; }
        public Nullable<int> numeroOrdenOptimizacion { get; set; }
        public Nullable<int> moneda { get; set; }
        public Nullable<double> puntos { get; set; }
        public Nullable<bool> siTotalizar { get; set; }
        public int empresa { get; set; }
        public Nullable<bool> siRepercusion { get; set; }
        public Nullable<bool> siActualizadoStock { get; set; }
        public string codigoModelo { get; set; }
        public string colorAux { get; set; }
        public string colorInterior { get; set; }
        public Nullable<bool> siFallebaHorizontal { get; set; }
        public Nullable<bool> siFallebaVertical { get; set; }
        public Nullable<double> alturaFalleba { get; set; }
        public Nullable<double> modificadorFalleba { get; set; }
        public Nullable<double> kg { get; set; }
        public Nullable<double> numeroBultos { get; set; }
        public Nullable<double> volumen { get; set; }
        public Nullable<byte> siOrigen3d { get; set; }
        public Nullable<double> alturaFalleba2 { get; set; }
        public Nullable<double> costeAnadido { get; set; }
        public Nullable<double> acumuladoCapitulo { get; set; }
        public Nullable<double> extraMarco { get; set; }
        public Nullable<byte> medidaEspecial { get; set; }
        public string variables { get; set; }
        public Nullable<double> extraVierteAguas { get; set; }
        public Nullable<bool> siDiferenteHoja { get; set; }
        public Nullable<bool> siDiferenteJunquillo { get; set; }
        public Nullable<bool> siDiferenteMarco { get; set; }
        public Nullable<bool> siPBandera { get; set; }
        public Nullable<bool> siVariasSeries { get; set; }
        public Nullable<bool> siVierteAguas { get; set; }
        public Nullable<bool> siSuplementosMarco { get; set; }
        public string seriePadre { get; set; }
        public Nullable<bool> siAcristalarConSilicona { get; set; }
        public Nullable<double> pesoNeto { get; set; }
        public Nullable<double> pesoBruto { get; set; }
        public Nullable<double> volumenPuntos { get; set; }
        public string observaciones { get; set; }
        public Nullable<bool> respetarPrecioCoste { get; set; }
        public Nullable<int> siDescripcionCreada { get; set; }
        public string descripcionTraducida { get; set; }
        public byte[] upsize_ts { get; set; }
        public Nullable<double> recubel { get; set; }
        public string dtoTipo { get; set; }
        public Nullable<int> idEscena { get; set; }
        public Nullable<double> incrVidrio { get; set; }
        public Nullable<bool> siRegalo { get; set; }
        public int idCatalogo { get; set; }
        public Nullable<double> valorPunto { get; set; }
        public Nullable<int> contadorUnico { get; set; }
        public Nullable<int> subcontadorUnico { get; set; }
        public Nullable<double> importeDescuento { get; set; }
        public Nullable<int> idCatalogoSerie { get; set; }
        public Nullable<int> tipoFachada { get; set; }
        public Nullable<double> totalm2 { get; set; }
        public Nullable<double> cte { get; set; }
        public Nullable<double> unidadesVersionadas { get; set; }
        public Nullable<int> montaje { get; set; }
        public string incrementos { get; set; }
        public string erroresProcesos { get; set; }
        public string descripcion3D { get; set; }
        public Nullable<double> precioInc { get; set; }
        public Nullable<bool> respetarDescripcion { get; set; }
        public Nullable<bool> siDescripcionTraducidaModificada { get; set; }
        public Nullable<int> tipoApertura { get; set; }
        public string tipoCerradura { get; set; }
        public Nullable<double> gruesoTabique { get; set; }
        public Nullable<int> numHojas { get; set; }
        public Nullable<int> numBisagras { get; set; }
        public Nullable<bool> noFabricar { get; set; }
        public byte[] imagenPartida { get; set; }
        public Nullable<bool> siImagenPartida { get; set; }
        public string sprecioinc { get; set; }
        public Nullable<double> importeCosteIndirecto { get; set; }
        public Nullable<double> costeAnadidoRetalesM2 { get; set; }
        public Nullable<double> importeCosteIndirectoVenta { get; set; }
        public string refext { get; set; }
        public Nullable<double> pvpRecomendado { get; set; }
        public Nullable<double> puntosMuebleBase { get; set; }
        public Nullable<int> ordenEnOptimizacion { get; set; }
        public Nullable<double> dtoFicticio { get; set; }
        public Nullable<double> importeUF { get; set; }
        public Nullable<int> idObra { get; set; }
        public string referencia2 { get; set; }
        public Nullable<int> tipoPartida { get; set; }
        public Nullable<bool> respetarObservaciones { get; set; }
        public Nullable<bool> respetarIdPartida { get; set; }
        public string mano { get; set; }
        public Nullable<int> tipoCategoria { get; set; }
        public Nullable<double> instalacionDirecta { get; set; }
        public Nullable<bool> precioModificado { get; set; }
        public string visible { get; set; }
        public bool EcoMobilierSometido { get; set; }
        public string EcoMobilierCodigo { get; set; }
        public Nullable<double> EcoMobilierImporte { get; set; }
        public bool EcoParticipationSometido { get; set; }
        public string EcoParticipationCodigo { get; set; }
        public Nullable<double> EcoParticipationImporte { get; set; }
        public bool TFASometido { get; set; }
        public double TFA { get; set; }
        public double taxaTVA { get; set; }
    }
}
